# Generated by Django 4.2.7 on 2023-12-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materials_is_published_alter_materials_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
